import type { CardData } from "@/components/cards/Card";
import { ART, ARTWORK_CREATED_AT, artworkPromptFor } from "../_card-helpers";

export const ELECTRONIC_CARDS: CardData[] = [
  {
    catalogNumber: 1,
    id: 3,
    title: "One More Time",
    year: "2000",
    genre: "House",
    ability: "Loop Sync",
    abilityDesc: "Repeats its effect once if experimental is above 60.",
    pop: 8,
    rarity: "CLASSIC",
    artwork: `${ART}daft-punk-one-more-time-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["daft-punk-one-more-time-v1.png"],
    ...(artworkPromptFor(3) ?? {}),
  },
  {
    catalogNumber: 2,
    id: 37,
    title: "Sky and Sand",
    year: "2008",
    genre: "Minimal",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "CLASSIC",
    artwork: `${ART}paul-karlkbrenner-sky-and-sand-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["paul-karlkbrenner-sky-and-sand-v1.png"],
    ...(artworkPromptFor(37) ?? {}),
  },
  {
    catalogNumber: 3,
    id: 42,
    title: "Levels",
    year: "2011",
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "LEGENDARY",
    artwork: `${ART}avicii-levels-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["avicii-levels-v1.png"],
    ...(artworkPromptFor(42) ?? {}),
  },
  {
    catalogNumber: 4,
    id: 45,
    title: "Gangnam Style",
    year: "2012",
    genre: "Electropop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "LEGENDARY",
    artwork: `${ART}psy-gagnam-style-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["psy-gagnam-style-v1.png"],
    ...(artworkPromptFor(45) ?? {}),
  },
  {
    catalogNumber: 5,
    id: 46,
    title: "Poker Face",
    year: "2008",
    genre: "Dance Pop",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "LEGENDARY",
    artwork: `${ART}lady-gaga-poker-face-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["lady-gaga-poker-face-v1.png"],
    ...(artworkPromptFor(46) ?? {}),
  },
  {
    catalogNumber: 7,
    id: 111,
    songsOut: [113],
    title: "Harder, Better, Faster, Stronger",
    year: "2001",
    genre: "French House",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "LEGENDARY",
    artwork: `${ART}daft-punk-harder-better-faster-stronger-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT[
        "daft-punk-harder-better-faster-stronger-v1.png"
      ],
  },
  {
    catalogNumber: 8,
    id: 58,
    title: "Shake It Off",
    artist: "",
    year: "2014",
    genre: "Mainstream",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "LEGENDARY",
    artwork: `${ART}taylor-swift-shake-it-off-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["taylor-swift-shake-it-off-v1.png"],
  },
  {
    catalogNumber: 9,
    id: 59,
    title: "Sandstorm",
    year: "1999",
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "LEGENDARY",
    artwork: `${ART}darude-sandstorm-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["darude-sandstorm-v1.png"],
    ...(artworkPromptFor(59) ?? {}),
  },
  {
    catalogNumber: 11,
    id: 109,
    songsOut: [110],
    title: "Mad World",
    artist: "",
    year: "1982",
    genre: "New Wave",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "CLASSIC",
    artwork: `${ART}tears-for-fears-mad-world-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["tears-for-fears-mad-world-v1.png"],
    ...(artworkPromptFor(109) ?? {}),
  },
  {
    catalogNumber: 12,
    id: 84,
    songsOut: [85],
    title: "Opus I",
    artist: "",
    year: "2015",
    genre: "EDM",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 9,
    rarity: "LEGENDARY",
    artwork: `${ART}eric-prydz-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["eric-prydz-opus-v1.png"],
  },
  {
    catalogNumber: 13,
    id: 85,
    songsOut: [86],
    title: "Opus II",
    artist: "",
    year: "2016",
    genre: "Progressive House",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "CLASSIC",
    artwork: `${ART}four-tet-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["four-tet-opus-v1.png"],
  },
  {
    catalogNumber: 14,
    id: 86,
    title: "Opus III",
    artist: "La Confrérie Lunatic",
    year: "2024",
    genre: "Peak Time Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "BANGER",
    artwork: `${ART}lunatic-opus-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["lunatic-opus-v1.png"],
  },
  {
    catalogNumber: 15,
    id: 90,
    title: "Vois sur ton chemin",
    artist: "",
    year: "2023",
    genre: "Hard Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "CLASSIC",
    artwork: `${ART}bennet-vois-sur-ton-chemin-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["bennet-vois-sur-ton-chemin-v1.png"],
    ...(artworkPromptFor(90) ?? {}),
  },
  {
    catalogNumber: 16,
    id: 93,
    title: "Superstition",
    artist: "C2C",
    year: "2012",
    genre: "Turntablism",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "BANGER",
    artwork: `${ART}c2c-superstition-v1.png`,
    artworkCreatedAt: ARTWORK_CREATED_AT["c2c-superstition-v1.png"],
    ...(artworkPromptFor(93) ?? {}),
  },
  {
    catalogNumber: 17,
    id: 108,
    artworkOffsetY: -50,
    title: "Losing Your Mind",
    artist: "",
    year: "2021",
    genre: "Peak Time Techno",
    ability: "Reserve",
    abilityDesc: "Shipped catalogue entry.",
    pop: 8,
    rarity: "BANGER",
    artwork: `${ART}adam-beyer-loosing-your-mind-v1.png`,
    artworkCreatedAt:
      ARTWORK_CREATED_AT["adam-beyer-loosing-your-mind-v1.png"],
    ...(artworkPromptFor(108) ?? {}),
  },
] as CardData[];
